### register 
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "username": "ningning",
    "email": "ningning@gmail.com",
    "password": "admin"
}

### login
POST http://localhost:8800/api/auth/login
Content-Type: application/json

{
    "email": "karina@gmail.com",
    "password": "admin"
}